# [[queries]]
# mesurement = "biz_users"
# value_fields = [ "total" ]
# label_fields = [ "service" ]
# metric_name_field = "x"
# timeout = "3s"
# request = '''
# select 'n9e' as service, 'test' as x, count(*) as total from n9e_v6.users
# '''