user = ""
password = ""
namespace = "redis"
connection_timeout = "1s"
ping_on_connect = true
set_client_name = true
is_tile38 = false
skip_tls_verification = true
client_cert_file = ""
client_key_file = ""
ca_cert_file = ""
include_system_metrics = true
include_config_metrics = true
redact_config_metrics = true

check_keys = []
check_single_keys = []
check_keys_batch_size = 1000
check_key_groups = []
max_distinct_key_groups = 100
check_streams = []
check_single_streams = []
count_keys = []
lua_script_files = []
disable_exporting_key_values = false
export_client_list = false
export_clients_include_port = false
